config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, module: :posts
    resource :like, module: :posts, only: [:update]
    resource :unlike, module: :posts, only: [:update]
  end

  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :profiles, except: [:new] do
    resource :follow, module: :profiles, only: [:update]
    resource :unfollow, module: :profiles, only: [:update]
  end

  resources :search, only: [:index]

  resources :collections

  root 'home#index'
end

app/controllers/profiles/follows_controller.rb
# frozen_string_literal: true

module Profiles
  class FollowsController < ApplicationController
    before_action :authenticate_user!

    def update
      @user = User.friendly.find(params[:profile_id])
      if current_user.follow(@user)
        redirect_to profile_path(@user), success: 'You now follow this profile!'
      else
        redirect_to profile_path(@user), alert: 'Something went wrong...'
      end
    end
  end
end

app/controllers/profiles/unfollows_controller.rb
# frozen_string_literal: true

module Profiles
  class UnfollowsController < ApplicationController
    before_action :authenticate_user!

    def update
      @user = User.friendly.find(params[:profile_id])

      if current_user.stop_following(@user)
        redirect_to profile_path(@user), success: "You unfollowed #{@user.username}!"
      else
        redirect_to profile_path(@user), alert: 'Something went wrong...'
      end
    end
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  # before_action :authenticate_user!

  def show
    @user = User.friendly.find(params[:id])
    @collections = @user.collections
    @posts = @user.posts.with_an_image.all.order_by_newest
  end
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
  def current_user_profile?(user)
    current_user == user
  end

  def not_current_user_profile?(user)
    !current_user_profile?(user)
  end

  def not_following_user?(user)
    not_current_user_profile?(user) && !current_user.following?(user)
  end

  def following_user?(user)
    not_current_user_profile?(user) && current_user.following?(user)
  end

  def show_link_if(condition, name, options = {}, html_options = {}, &block)
    if condition
      link_to(name, options, html_options)
    elsif block_given?
      block.arity <= 1 ? capture(name, &block) : capture(name, options, html_options, &block)
    end
  end
end

app/views/profiles/_collection.html.haml
.col-12.col-md-6.col-lg-4
  %article.article.article-style-c
    .article-user
      = collection.name
      .small
        %span= time_ago_in_words(collection.created_at)
    .article-header
      = link_to collection_path(collection) do
        .article-image{style: "background-image: url('#{ rails_representation_url(collection.posts.first.image.variant(resize_to_limit: [500, nil]).processed)}')"}

app/views/profiles/_post.html.haml
.col-12.col-md-6.col-lg-4
  %article.article.article-style-c
    .article-user
      = post.user.username
      .small
        %span= time_ago_in_words(post.created_at)
    .article-header
      = link_to post_path(post) do
        .article-image{style: "background-image: url('#{ rails_representation_url(post.image.variant(resize_to_limit: [500, nil]).processed)}')"}

app/views/profiles/show.html.haml
.col-12.col-md-12.mt-5
    .card.profile-widget
        .profile-widget-header
            - if user_avatar(@user).present?
                .rounded-circle.profile-widget-picture.mt-2= image_tag user_avatar(@user), class: 'rounded-circle'
            .profile-widget-items
                %h2.profile-widget-name= @user.username
                .profile-widget-buttons.mt-2.ml-3
                    = show_link_if current_user_profile?(@user), 'Edit profile', edit_user_registration_path(@user), class: 'btn btn-sm btn-primary'
                    = show_link_if not_following_user?(@user), 'Follow', profile_follow_path(@user), method: :patch, class: 'follow btn btn-sm btn-primary'
                    = show_link_if following_user?(@user), 'Unfollow', profile_unfollow_path(@user), method: :patch, class: 'unfollow btn btn-sm btn-primary'
            .profile-widget-items
                .profile-widget-item
                    .profile-widget-item-label Posts
                    .profile-widget-item-value= @user.posts.count
                .profile-widget-item
                    .profile-widget-item-label Followers
                    .profile-widget-item-value= @user.followers.count
                .profile-widget-item
                    .profile-widget-item-label Following
                    .profile-widget-item-value= @user.following_users.count
        .profile-widget-description
            .profile-widget-name
            = @user.full_name
            .profile-widget-buttons.mt-2.ml-3
            %hr
            .text-muted.d-inline.font-weight-normal
                = @user.bio
    %hr
    -unless @collections.empty?
        %ul#pills-tab.nav.nav-pills.mb-3{:role => "tablist"}
            %li.nav-item
                %a#pills-home-tab.nav-link.active{"aria-controls" => "pills-home", "aria-selected" => "true", "data-toggle" => "pill", :href => "#pills-home", :role => "tab"} Posts
            %li.nav-item
                %a#pills-profile-tab.nav-link{"aria-controls" => "pills-profile", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-profile", :role => "tab"} Collections
        #pills-tabContent.tab-content
            #pills-home.tab-pane.fade.show.active{"aria-labelledby" => "pills-home-tab", :role => "tabpanel"}
                .row
                    -if @posts.empty?
                        %p This user does not have any posts yet
                    -else
                        = render @posts
            #pills-profile.tab-pane.fade{"aria-labelledby" => "pills-profile-tab", :role => "tabpanel"}
                .row
                    = render @collections
    -else
        .row
            -if @posts.empty?
                %p This user does not have any posts yet
            -else
                = render @posts