config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, module: :posts
    resource :like, module: :posts, only: [:update]
    resource :unlike, module: :posts, only: [:update]
  end

  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :profiles, except: [:new] do
    resource :follow, module: :profiles, only: [:update]
    resource :unfollow, module: :profiles, only: [:update]
  end

  resources :search, only: [:index]

  resources :collections

  root 'home#index'
end

app/models/collection.rb
# frozen_string_literal: true

class Collection < ApplicationRecord
  has_many :collection_posts, dependent: :destroy
  has_many :posts, through: :collection_posts
  has_many :collection_users, dependent: :destroy
  has_many :users, through: :collection_users
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversations = current_user.mailbox.conversations
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.mark_as_read(current_user)
    @message = Mailboxer::Message.new
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    participants_id = (params[:user_ids].map(&:to_i) + [current_user.id]).sort
    conversations = current_user.mailbox.conversations
    past_conversations = conversations.map do |c|
      { conversation: c, participants_id: c.participants.pluck(:id).sort }
    end

    existing_conversation = past_conversations.select { |c| c[:participants_id] == participants_id }.first

    if existing_conversation.nil?
      recipients = User.where(id: params[:user_ids])
      receipt = current_user.send_message(recipients, params[:body], '-')
      conversation = receipt.conversation
      redirect_to conversation_path(conversation)
    else
      current_user.reply_to_conversation(existing_conversation[:conversation], params[:body], nil)
      redirect_to conversation_path(existing_conversation[:conversation])
    end
  end
end

app/helpers/conversations_helper.rb
# frozen_string_literal: true

module ConversationsHelper
  def penpal(conversation)
    conversation.participants.without(current_user)
  end

  def penpal_usernames(conversation)
    conversation.participants.without(current_user).map(&:username).join(', ')
  end
end

app/views/conversations/index.html.haml
.messaging
    .row.inbox_msg
        .msg.col-12.col-md-8.col-lg-8
            #chat-box.card.chat-box{:style => "height:90%;"}
                .card-body.chat-content
                    .d-flex.justify-content-center.align-items-center{:style => "height:100%;"}
                        %p Select a conversation, or start a new one
                        = link_to 'New Message', new_conversation_path, class: 'btn btn-sm btn-primary ml-3 mb-3'
        .inbox_people.col-12.col-md-4.col-lg-4
            .row.card
                .card-header.justify-content-center
                    %h4= current_user.username
                .card-body
                    %ul.list-unstyled.list-unstyled-border
                        - @conversations.each do |c|
                            %li.media
                                - penpal(c).each do |p|
                                    = image_tag(user_avatar(p), alt: 'image', width: '50', :class => "mr-3 rounded-circle")
                                .media-body
                                    .mt-0.mb-1.font-weight-bold
                                        - if c.is_unread?(current_user)
                                            %strong= link_to penpal_usernames(c), conversation_path(c)
                                        - else
                                            = link_to penpal_usernames(c), conversation_path(c)

app/views/conversations/new.html.haml
%h1 New Conversation
= form_tag conversations_path, method: :post do |c|
    %div= select_tag :user_ids, options_from_collection_for_select(@recipients, :id, :username), multiple: true
    %div= text_area_tag :body, nil, placeholder: 'Leave a comment'
    = submit_tag

app/views/conversations/show.html.haml
.messaging
    .inbox_msg.row
        .msg.col-12.col-md-8.col-lg-8
            #chat-box.card.chat-box{:style => "height:90%;"}
                .card-header
                    Chat with #{penpal_usernames(@conversation)}
                .card-body.chat-content{:style => "overflow: hidden; outline: none; height:90%;", :tabindex => "2"}
                    - @conversation.receipts_for(current_user).each do |r|
                        -if r.message.sender == current_user
                            .chat-item.chat-right
                                = image_tag(user_avatar(r.message.sender), alt: 'image', width: '50', :class => "mr-3 rounded-circle")
                                .chat-details
                                    .chat-text
                                        = simple_format r.message.body
                                    .chat-time= r[:created_at].strftime("%I:%M %P")
                        -else
                            .chat-item.chat-left
                                = image_tag(user_avatar(r.message.sender), alt: 'image', width: '50', :class => "mr-3 rounded-circle")
                                .chat-details
                                    .chat-text
                                        = simple_format r.message.body
                                    .chat-time= r[:created_at].strftime("%I:%M %P")
                .card-footer.chat-form
                    = form_for @message, url: conversation_messages_path(@conversation), html: { class: 'form-row', id: 'chat-form2' } do |f|
                        .col-11
                            = f.text_area :body, placeholder: 'Type a message', type: 'text', class: 'form-control'
                        .col-1
                            = button_tag class: 'btn btn-primary' do
                                %i.far.fa-paper-plane
        .inbox_people.col-12.col-md-4.col-lg-4
            .row.card
                .card-header.justify-content-center
                    %h4= current_user.username
                .card-body
                    %ul.list-unstyled.list-unstyled-border
                        - @conversations.each do |c|
                            %li.media
                                - penpal(c).each do |p|
                                    = image_tag(user_avatar(p), alt: 'image', width: '50', :class => "mr-3 rounded-circle")
                                .media-body
                                    .mt-0.mb-1.font-weight-bold
                                        - if c.is_unread?(current_user)
                                            %strong= link_to penpal_usernames(c), conversation_path(c)
                                        - else
                                            = link_to penpal_usernames(c), conversation_path(c)