config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, module: :posts
    resource :like, module: :posts, only: [:update]
    resource :unlike, module: :posts, only: [:update]
  end

  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :profiles, except: [:new] do
    resource :follow, module: :profiles, only: [:update]
    resource :unfollow, module: :profiles, only: [:update]
  end

  resources :search, only: [:index]

  resources :collections

  root 'home#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  searchkick
  acts_as_favoritable
  acts_as_taggable_on :tags

  belongs_to :user
  has_one_attached :image
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :collection_posts, dependent: :destroy
  has_many :collections, through: :collection_posts

  scope :with_an_image, -> { includes(:image_attachment).where.not(active_storage_attachments: { record_id: nil }) }
  scope :order_by_newest, -> { order(created_at: :desc) }
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < CommentsController
    before_action :set_commentable

    private

    def set_commentable
      @commentable = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

module Posts
  class LikesController < ApplicationController
    before_action :authenticate_user!

    def update
      @post = Post.find(params[:post_id])

      if current_user.favorite(@post)
        respond_to do |format|
          format.html { redirect_to @post, success: 'You now like this post!' }
          format.js { head :created }
        end
      else
        redirect_to @post, alert: 'Something went wrong'
      end
    end
  end
end

app/controllers/posts/unlikes_controller.rb
# frozen_string_literal: true

module Posts
  class UnlikesController < ApplicationController
    before_action :authenticate_user!

    def update
      @post = Post.find(params[:post_id])

      if current_user.unfavorite(@post)
        respond_to do |format|
          format.html { redirect_to @post, success: 'You now unlike this post' }
          format.js { head :ok }
        end
      else
        redirect_to @post, alert: 'Something went wrong'
      end
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.with_an_image.all.order_by_newest
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:description, :image, :tag_list)
  end
end

app/views/posts/_add_to_collection.html.haml
= link_to collections_path, data: { 'toggle': 'tooltip', 'original-title': 'Add to collection' } do
    %i.fas.fa-list-ul

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |f|
    .form-group
        = f.label :image
        = f.file_field :image
        - if post.image.persisted?
            = image_tag post.image
    .form-group
        = f.label :description
        = f.text_field :description
        = f.submit 'Create post', class: 'btn btn-primary', method: :post

app/views/posts/_likes.html.haml
= turbo_stream_from 'likes'

%turbo-stream{action: 'update', target: 'like_count'}
  %template
    = "#{post.favoritors.count} like this"

%turbo-stream{action: 'update', target: 'like_heart'}
  %template
    - if current_user.favorited?(post)
      = link_to post_unlike_path(post), remote: true, method: :patch, class: 'unlike' do
        %i.fas.fa-heart
    - else
      = link_to post_like_path(post), remote: true, method: :patch, class: 'like' do
        %i.far.fa-heart


#like_count

%span#like_heart

app/views/posts/index.html.haml
%h1 All posts
= link_to 'Create a post', new_post_path, class: 'btn btn-success'
%hr/
.row
  = render @posts

app/views/posts/new.html.haml
%h1 Create a Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.haml
.page-header
    =link_to 'All posts', posts_path, class: 'btn btn-default'
    =link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary'
    %h3 Show post
%dl.dl-horizontal
    - if @post.image.persisted?
        %dt Image:
        %dd= image_tag @post.image.variant(resize_to_limit: [500, nil])
    %dt Description:
    %dd= @post.description

= render 'likes', post: @post, current_user: current_user

= render 'add_to_collection'

%h3 Comments:
= render partial: "comments/form", locals: { commentable: @post }
= render @post.comments.where(parent_id: nil)