config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, module: :posts
    resource :like, module: :posts, only: [:update]
    resource :unlike, module: :posts, only: [:update]
  end

  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :profiles, except: [:new] do
    resource :follow, module: :profiles, only: [:update]
    resource :unfollow, module: :profiles, only: [:update]
  end

  resources :search, only: [:index]

  resources :collections

  root 'home#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[username]

    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: [added_attrs, :avatar, :full_name, :bio])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# rubocop:disable Style/GuardClause
module ApplicationHelper
  def user_avatar(user, size = 200)
    if user.avatar.attached?
      user.avatar.variant(resize_to_fill: [size, size,
                                           { gravity: 'Center' }])
    else
      'avatar.png'
    end
  end
end
# rubocop:enable Style/GuardClause

app/views/application/_navigation.html.haml
%nav.navbar.navbar-expand-lg.bg-primary
  .container.custom
    .div
      .navbar-brand
        = link_to 'Unframed', root_path, class: 'nav-link'
    .div.custom
      = render 'search'
    .div.custom
      #navbarNav.collapse.navbar-collapse
      - unless user_signed_in?
        .div
          .nav-item
            = link_to 'Sign in', new_user_session_path, class: 'nav-link', data: { id: 'link-to-login' }
      - else
        .div.custom
          .nav-item
            = link_to new_post_path, class: 'nav-link', data: { 'toggle': 'tooltip', 'original-title': 'Create post', 'id': 'link-to-new-post' } do
              %i.fas.fa-plus
          .nav-item
            = link_to posts_path, class: 'nav-link', data: { 'toggle': 'tooltip', 'original-title': 'Timeline' } do
              %i.fas.fa-home
          .nav-item
            = link_to conversations_path, class: 'nav-link', data: { 'toggle': 'tooltip', 'original-title': 'Inbox' } do
              %i.fas.fa-inbox
          .nav-item
            = link_to profile_path(current_user), class: 'nav-link', data: { 'toggle': 'tooltip', 'original-title': 'Your profile' } do
              %i.far.fa-user
        .div
          .nav-item
            = link_to 'Sign Out', destroy_user_session_path, class: 'nav-link', method: :delete

app/views/application/_search.html.haml
= form_with(url: search_index_path, method: :get, class: 'form-inline') do |f|
  = f.text_field :q, value: params[:q], class: 'form-control', placeholder: 'Search', 'aria-label' => 'Search'
  %button.btn{:type => 'submit'}
    %i.fas.fa-search{'aria-hidden' => 'true'}